import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./components/common/NavbarWrapper";
import FooterWrapper from "./components/common/FooterWrapper";
import { Toaster } from "react-hot-toast";
import { AppContextProvider } from "@/contexts/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppContextProvider>
          <NavbarWrapper />
            {children}
            <Toaster
              position="top-center"
              reverseOrder={false}
            />
          <FooterWrapper />
        </AppContextProvider>
      </body>

    </html>
  );
}
